# Generated by Django 6.0.4 on 2026-05-01 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField()),
                ('glucose', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('skin_thickness', models.FloatField()),
                ('insulin', models.FloatField()),
                ('bmi', models.FloatField()),
                ('dpf', models.FloatField(verbose_name='Diabetes Pedigree Function')),
                ('age', models.IntegerField()),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('risk_level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Prediction Record',
                'ordering': ['-created_at'],
            },
        ),
    ]
