# Generated by Django 6.0.4 on 2026-05-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='ca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='chol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='cp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='disease',
            field=models.CharField(choices=[('diabetes', 'Diabetes'), ('heart', 'Heart Disease')], default='diabetes', max_length=20),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='exang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='fbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='oldpeak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='restecg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='sex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='slope',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='thal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='thalach',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='trestbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='blood_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='dpf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='insulin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='prediction',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='pregnancies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='skin_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
